# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build C++

on:
  push:
    branches:
      - main
    paths:
      - "CMakeLists.txt"
      - "**/*.cpp"
      - "**/*.h"
      - "**/*.hpp"
      - "**/*.cxx"
      - "**/*.c"
      - ".github/workflows/build_and_test.yml"
  pull_request:
    branches:
      - main

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build
  CPP_STANDARD: 20
jobs:
  build_cpp20:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/honigkuchen/${{ github.event.repository.name }}
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -B ${{env.BUILD_DIR}} \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DCMAKE_CXX_STANDARD=${{env.CPP_STANDARD}}
          cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}

      - name: Test
        run: |
          ctest -C ${{env.BUILD_TYPE}}
