# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build C++

on:
  workflow_call:
    inputs:
      CPP_STANDARD:
        required: true
        type: string

env:
  BUILD_TYPE: Release
  BUILD_DIR: /tmp/build
  CPP_STANDARD: 20

jobs:
  build_cpp20:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/honigkuchen/${{ github.event.repository.name }}
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          cmake --preset GithubMakefileConfigurationPreset
          cmake --build --preset GithubMakefileBuildPreset

      - name: Test
        working-directory: ${{env.BUILD_DIR}}
        run: |
          ctest \
            -C ${{env.BUILD_TYPE}} \
            --test-dir test \
            --output-junit junit_result.xml \
            --output-on-failure

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: Test results
          path: ${{env.BUILD_DIR}}/test/junit_result.xml
          if-no-files-found: error

      - name: Benchmark
        run: |
          ${{env.BUILD_DIR}}/benchmark/cpp-cmake-default_benchmark --v=2

      - name: Benchmark to file
        run: |
          ${{env.BUILD_DIR}}/benchmark/cpp-cmake-default_benchmark \
            --benchmark_out=${{env.BUILD_DIR}}/benchmark/benchmark.json \
            --benchmark_out_format=json \
            --v=2
      
      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: Benchmark results
          path: ${{env.BUILD_DIR}}/benchmark/benchmark.json
          if-no-files-found: error